### ISSUE TITLE
Json error

### ISSUE THREAD

**Issue by vem882** [Deathknife/sourcemod-discord#1]
L 01/10/2017 - 00:22:36: [SMJSON] Error in line 1, col 106: end of file expected near 'tion'
L 01/10/2017 - 00:22:36: [SM] Exception reported: Invalid <Object> handle 0 (error 4)
L 01/10/2017 - 00:22:36: [SM] Blaming: discord_api.smx()
L 01/10/2017 - 00:22:36: [SM] Call stack trace:
L 01/10/2017 - 00:22:36: [SM]   [0] json_array_size
L 01/10/2017 - 00:22:36: [SM]   [1] Line 76, discord/GetGuilds.sp::GetGuildsData_Data()
L 01/10/2017 - 00:22:36: [SM]   [3] SteamWorks_GetHTTPResponseBodyCallback
L 01/10/2017 - 00:22:36: [SM]   [4] Line 31, discord/GetGuilds.sp::GetGuildsData()
L 01/10/2017 - 00:23:33: [SMJSON] Error in line 1, col 104: end of file expected near 'ti'
L 01/10/2017 - 00:23:33: [SM] Exception reported: Invalid <Object> handle 0 (error 4)
L 01/10/2017 - 00:23:33: [SM] Blaming: discord_api.smx()
L 01/10/2017 - 00:23:33: [SM] Call stack trace:
L 01/10/2017 - 00:23:33: [SM]   [0] json_array_size
L 01/10/2017 - 00:23:33: [SM]   [1] Line 76, discord/GetGuilds.sp::GetGuildsData_Data()
L 01/10/2017 - 00:23:33: [SM]   [3] SteamWorks_GetHTTPResponseBodyCallback
L 01/10/2017 - 00:23:33: [SM]   [4] Line 31, discord/GetGuilds.sp::GetGuildsData()

**Comment by Deathknife** [comment]
What plugin is trying to get guilds? If it's one from the examples, did you change the <Bot Token> in .sp and compiled it yourself?

**Comment by vem882** [comment]
Discord_test and i changet only token.
Calladmin function works fine.

**Comment by Deathknife** [comment]
If Call Admin works then there shouldn't be any reason discord_test would not. I cannot replicate this issue.


I have attached a modified discord_api plugin. It will log raw string it receives for listing Get Guilds(which is where the error is caused). It will log it into sourcemod logs and should print to console as well. Could you please put the `discord_api.smx` (or compile yourself from source) on server, then do `sm_getguilds` and reply here with the message? It should start with something like:


`[DISCORD] GETTING CHANNELS: DATA RETRIEVED:`


[test.zip](https://github.com/Deathknife/sourcemod-discord/files/697550/test.zip)

**Comment by vem882** [comment]
Server Console log:
`L 01/11/2017 - 00:27:42: Loading map "achievement_idle_awesomeboxo31"
L 01/11/2017 - 00:27:42: [discord_api.smx] [DISCORD] GETTING CHANNELS: DATA RETRIEVED: '[{"owner": false, "permissions": 2146958463, "icon": null, "id": "268100550195675136", "name": "D54"}]role", "id": "268100550195675136", "allow": 333889}, {"deny": 0, "type": "role", "id": "268133218304131072", "allow": 0}, {"deny": 0, "type": "role", "id": "268133007766847499", "allow": 0}], "topic": "", "position": 0, "last_message_id": "268495438498234369", "type": "text", "id": "268100550195675136", "is_private": false}, {"permission_overwrites": [], "name": "General", "user_limit": 0, "type": "voice", "position": 0, "guild_id": "268100550195675136", "bitrate": 64000, "id": "268100550195675137", "is_private": false}, {"guild_id": "268100550195675136", "name": "call-admin", "permission_overwrites": [{"deny": 0, "type": "member", "id": "268099721673965568", "allow": 805829713}, {"deny": 805821521, "type": "role", "id": "268100550195675136", "allow": 0}, {"deny": 0, "type": "member", "id": "268103454562451456", "allow": L 01/11/2017 - 00:27:42: [SMJSON] Error in line 1, col 106: end of file expected near 'role'
L 01/11/2017 - 00:27:42: [SM] Exception reported: Invalid <Object> handle 0 (error 4)
L 01/11/2017 - 00:27:42: [SM] Blaming: discord_api.smx()
L 01/11/2017 - 00:27:42: [SM] Call stack trace:
L 01/11/2017 - 00:27:42: [SM]   [0] json_array_size
L 01/11/2017 - 00:27:42: [SM]   [1] Line 102, discord/GetGuilds.sp::GetGuildsData_Data()
L 01/11/2017 - 00:27:42: [SM]   [3] SteamWorks_GetHTTPResponseBodyCallback
L 01/11/2017 - 00:27:42: [SM]   [4] Line 56, discord/GetGuilds.sp::GetGuildsData()
sm_getguilds
L 01/11/2017 - 00:28:24: [SM] Exception reported: Client index 0 is invalid
L 01/11/2017 - 00:28:24: [SM] Blaming: discord_test.smx()
L 01/11/2017 - 00:28:24: [SM] Call stack trace:
L 01/11/2017 - 00:28:24: [SM]   [0] GetClientUserId
L 01/11/2017 - 00:28:24: [SM]   [1] Line 28, discord_test.sp::Cmd_GetGuilds()
`

Tf2 console: 
`
] sm_getguilds
Trying!
`
Sourcemod errorlog:
`L 01/11/2017 - 00:27:42: [SMJSON] Error in line 1, col 106: end of file expected near 'role'
L 01/11/2017 - 00:27:42: [SM] Exception reported: Invalid <Object> handle 0 (error 4)
L 01/11/2017 - 00:27:42: [SM] Blaming: discord_api.smx()
L 01/11/2017 - 00:27:42: [SM] Call stack trace:
L 01/11/2017 - 00:27:42: [SM]   [0] json_array_size
L 01/11/2017 - 00:27:42: [SM]   [1] Line 102, discord/GetGuilds.sp::GetGuildsData_Data()
L 01/11/2017 - 00:27:42: [SM]   [3] SteamWorks_GetHTTPResponseBodyCallback
L 01/11/2017 - 00:27:42: [SM]   [4] Line 56, discord/GetGuilds.sp::GetGuildsData()
L 01/11/2017 - 00:28:24: [SM] Exception reported: Client index 0 is invalid
L 01/11/2017 - 00:28:24: [SM] Blaming: discord_test.smx()
L 01/11/2017 - 00:28:24: [SM] Call stack trace:
L 01/11/2017 - 00:28:24: [SM]   [0] GetClientUserId
L 01/11/2017 - 00:28:24: [SM]   [1] Line 28, discord_test.sp::Cmd_GetGuilds()
L 01/11/2017 - 00:28:33: [SM] Exception reported: Client index 0 is invalid
L 01/11/2017 - 00:28:33: [SM] Blaming: discord_test.smx()
L 01/11/2017 - 00:28:33: [SM] Call stack trace:
L 01/11/2017 - 00:28:33: [SM]   [0] GetClientUserId
L 01/11/2017 - 00:28:33: [SM]   [1] Line 28, discord_test.sp::Cmd_GetGuilds()
L 01/11/2017 - 00:29:21: [SMJSON] Error in line 1, col 104: end of file expected near 'ro'
L 01/11/2017 - 00:29:21: [SM] Exception reported: Invalid <Object> handle 0 (error 4)
L 01/11/2017 - 00:29:21: [SM] Blaming: discord_api.smx()
L 01/11/2017 - 00:29:21: [SM] Call stack trace:
L 01/11/2017 - 00:29:21: [SM]   [0] json_array_size
L 01/11/2017 - 00:29:21: [SM]   [1] Line 102, discord/GetGuilds.sp::GetGuildsData_Data()
L 01/11/2017 - 00:29:21: [SM]   [3] SteamWorks_GetHTTPResponseBodyCallback
L 01/11/2017 - 00:29:21: [SM]   [4] Line 56, discord/GetGuilds.sp::GetGuildsData()
`

**Comment by Deathknife** [comment]
Use triple \` instead of single so it keeps line breaks.
```
[{"owner": false, "permissions": 2146958463, "icon": null, "id": "268100550195675136", "name": "D54"}]role", "id":
```
This seems wrong, can you ensure SteamWorks is up to date?

Also, try sending HTTP request (i.e requestmaker.com ) to:
https://discordapp.com/api/users/@me/guilds
Method: GET
Headers:
`Content-Type` = `application/json`
`Authorization` = `Bot ` (insert bot token)

and reply with response. Want to see if somehow it's discord or just something on server like steamworks or plugin.

**Comment by vem882** [comment]
Hahah.. yes! the problems was been in SteamWorks. I updated SteamWorks and now all works! Thank you so much!

SteamWorks:
http://users.alliedmods.net/~kyles/builds/SteamWorks/
