### ISSUE TITLE
Missing native

### ISSUE THREAD

**Issue by Diniboy1123** [Deathknife/sourcemod-discord#13]
Hi,

I tried to compile the example and the compilation is sucessfull. But on load, I always get this:

```
 Native "DiscordBot.StartTimer" was not found.
```

What can I do?

Many thanks!

**Comment by Diniboy1123** [comment]
Solved.

**Comment by alerad** [comment]
@Diniboy1123 would be cool if you explain how you solved it, facing same issue.

**Comment by yenf0ng** [comment]
help i face this issue @alerad @Diniboy1123
