### ISSUE TITLE
WebSocket issue

### ISSUE THREAD

**Issue by Flegma** [Deathknife/sourcemod-discord#2]
Hello,
ive compiled your example plugins (only changed bot token in calladmin) and i've gor smx files which i uploaded and the plugins seems to work.
But the Bot on the discord seems to not be working. I've created a bot user, even added it to the server, but the websocket connection (in chrome console) is giving me the error:
http://take.ms/GsExtE

**Comment by Deathknife** [comment]
Try to execute the 3 commands seperately. i.e

`var ws = new WebSocket('wss://gateway.discord.gg');`

Wait a second or two, then:
`var mystring = JSON.stringify({
 "op": 2,
 "d": {
 "token": "<bot token>",
 "properties": {
 "$os": "linux",
 "$browser": "sometestingbrowser",
 "$device": "sometestingdevice",
 "$referrer": "",
 "$referring_domain": "",
 },
 "compress": true,
 "large_threshold": 250,
 }
});`

and finally:
` ws.send(mystring);`

**Comment by Flegma** [comment]
Another error:

VM1459:35 Refused to connect to 'wss://gateway.discord.gg/' because it violates the following Content Security Policy directive: "connect-src 'self' uploads.github.com status.github.com collector.githubapp.com api.github.com www.google-analytics.com github-cloud.s3.amazonaws.com wss://live.github.com".

WrappedWebSocket @ VM1459:35
(anonymous) @ VM1812:1
VM1459:35 Uncaught DOMException: Failed to construct 'WebSocket': Refused to connect to 'wss://gateway.discord.gg/' because it violates the document's Content Security Policy.
    at WrappedWebSocket (<anonymous>:35:21)
    at <anonymous>:1:10

**Comment by Deathknife** [comment]
Solved by opening console on another page such as `google.com`

**Comment by ThreshHNS** [comment]
![image](https://cloud.githubusercontent.com/assets/24918680/21835657/c2cd8670-d7f9-11e6-987a-99d009256194.png)
It's fine?
