### ISSUE TITLE
Announcements are not arriving on the server

### ISSUE THREAD

**Issue by Xenoadria** [Deathknife/sourcemod-discord#3]
Hey mate. Few days ago you were helping Flegmoar and me to set this up. Everything was working till now.
Tried to send announcements on all my servers, none of them arrived. Checking up the logs i found this error:
L 01/13/2017 - 13:01:17: [SM] Exception reported: Invalid Handle d3f006c (error 1)
L 01/13/2017 - 13:01:17: [SM] Blaming: discord_api.smx
L 01/13/2017 - 13:01:17: [SM] Call stack trace:
L 01/13/2017 - 13:01:17: [SM]   [0] GetTrieString
L 01/13/2017 - 13:01:17: [SM]   [1] Line 36, F:\cloud\sourcemod\sourcepawn\configs\sm_one_seven_smlib_zero_nine_seven\include\discord.inc::DiscordChannel.GetID
L 01/13/2017 - 13:01:17: [SM]   [2] Line 10, discord/ListenToChannel.sp::GetMessages
L 01/13/2017 - 13:01:17: [SM]   [3] Line 55, discord/ListenToChannel.sp::CheckMessageTimer
L 01/13/2017 - 13:01:17: [discord_api.smx] [DISCORD] Couldn't Retrieve Messages - Fail 0 400

**Comment by Deathknife** [comment]
Can't replicate. Can you ensure all discord plugins(specially discord_api) are up to date and try again?

**Comment by xSnowyAngel** [comment]
Im having this issue too, it randomly stops working (even after map change) and i need to replace the file for it work again

**Comment by Deathknife** [comment]
I'm currently redoing a lot of the base system that should have this problem fixed. Should be ready in a day or two if everything goes good.

**Comment by Deathknife** [comment]
Try now @xSnowyAngel

**Comment by xSnowyAngel** [comment]
Try the new api?

**Comment by Deathknife** [comment]
Yeah
